management:
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
    
    metrics:
      enabled: true
    
    prometheus:
      enabled: true

    loggers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    export:
      prometheus:
        enabled: true

spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  
  application:
    name: census

  profiles:
    active: default
  
---
spring:
  profiles: default

server:
  port: ${SERVER.PORT:1301}
  
---
spring:
  profiles: resilience

server:
  port: ${SERVER.PORT:1301}
    
        