management:
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
    
    metrics:
      enabled: true
    
    prometheus:
      enabled: true

    loggers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    export:
      prometheus:
        enabled: true

spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  
  application:
    name: census

  profiles:
    active: default
  
---
spring:
  profiles: default

server:
  port: ${SERVER.PORT:1301}

  
---
spring:
  profiles: resilience

server:
  port: ${SERVER.PORT:1301}
    
            
---
spring:
  profiles: consul

  cloud:
    consul:
      host: ${CONSUL.IP:localhost}
      port: ${CONSUL.PORT:8500}

      config:
        enabled: true      
      
      discovery:
        instanceId: "${spring.application.name}:${random.int[1,999999]}"
      
server:
  port: ${SERVER.PORT:1301}
