version: '3'

services:
  kong:
    container_name: tutorial-kong
    image: kong:2.0.4
    networks:
      default:
        ipv4_address: 192.168.255.250    
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    environment:
      - KONG_DNS_RESOLVER=192.168.255.241:8600
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=192.168.255.249
      - KONG_PG_PASSWORD=k0ngc0nsvl
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes:
      - kong_data:/etc/kong

  konga:
    container_name: tutorial-konga
    image: pantsel/konga
    networks:
      default:
        ipv4_address: 192.168.255.252
    ports:
      - 1337:1337
    environment:
      - NODE_ENV=production
      - DB_ADAPTER=postgres
      - DB_HOST=192.168.255.249
      - DB_USER=kong
      - DB_PASSWORD=k0ngc0nsvl
      - DB_DATABASE=konga_db
      - KONGA_HOOK_TIMEOUT=120000

volumes:
  kong_data:

networks:
  default:
    external:
      name: census-net
