version: '3'

services:
  consul-server-1:
    container_name: tutorial-consul-server-1
    image: consul:1.8.0
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
    environment:
      CONSUL_LOCAL_CONFIG: >-
        {
          "server": true,
          "node_name": "tutorial-consul-server-1",
          "bind_addr": "0.0.0.0",
          "client_addr": "0.0.0.0",
          "bootstrap_expect": 3,
          "ui": true,
          "addresses" : {
            "http" : "0.0.0.0"
          },
          "telemetry": {
            "prometheus_retention_time": "24h",
            "disable_hostname": true
          },
          "connect" : {
            "enabled" : true
          }        
        }    
    command: "agent"
    
  consul-server-2:
    container_name: tutorial-consul-server-2
    image: consul:1.8.0
    environment:
      CONSUL_LOCAL_CONFIG: >-
        {
          "server": true,
          "node_name": "tutorial-consul-server-2",
          "bind_addr": "0.0.0.0",
          "client_addr": "0.0.0.0",
          "addresses" : {
            "http" : "0.0.0.0"
          },
          "connect" : {
            "enabled" : true
          }        
        }    
    command: "agent -retry-join tutorial-consul-server-1"
    
  consul-server-3:
    container_name: tutorial-consul-server-3
    image: consul:1.8.0
    environment:
      CONSUL_LOCAL_CONFIG: >-
        {
          "server": true,
          "node_name": "tutorial-consul-server-3",
          "bind_addr": "0.0.0.0",
          "client_addr": "0.0.0.0",
          "addresses" : {
            "http" : "0.0.0.0"
          },
          "connect" : {
            "enabled" : true
          }        
        }    
    command: "agent -retry-join tutorial-consul-server-1"

  consul-agent-1:
    container_name: tutorial-consul-agent-1
    image: consul:1.8.0
    command: "agent -retry-join tutorial-consul-server-1 -client 0.0.0.0 -bind 0.0.0.0"

  consul-agent-2:
    container_name: tutorial-consul-agent-2
    image: consul:1.8.0
    command: "agent -retry-join tutorial-consul-server-1 -client 0.0.0.0 -bind 0.0.0.0"

networks:
  default:
    external:
      name: consul-net
