version: '3'

services:
  consul-server-1:
    container_name: tutorial-consul-server-1
    image: consul:1.8.0
    restart: always
    ports:
      - 18300:8300
      - 18301:8301
      - 18301:8301/udp
      - 18302:8302
      - 18302:8302/udp
      - 18400:8400
      - 18500:8500
      - 18600:8600
      - 18600:8600/udp
    networks:
        default:
            ipv4_address: 192.168.255.241
    environment:
      CONSUL_LOCAL_CONFIG: >-
        {
          "bootstrap_expect": 3,
          "client_addr": "0.0.0.0",
          "datacenter": "Us-Central",
          "data_dir": "/var/consul",
          "domain": "consul",
          "enable_script_checks": true,
          "dns_config": {
              "enable_truncate": true,
              "only_passing": true
          },
          "encrypt": "6uZf92Qa7dFgGnQ1zh8Hn0MwnRh1bRAOlE481Mv4+cU=",
          "leave_on_terminate": true,
          "log_level": "INFO",
          "rejoin_after_leave": true,
          "server": true,
          "telemetry": {
              "prometheus_retention_time": "24h",
              "disable_hostname": true
          },                
          "start_join": [
              "192.168.255.241",
              "192.168.255.242",
              "192.168.255.243"
          ],
          "ui": true
        }
    command: "agent"
    
  consul-server-2:
    container_name: tutorial-consul-server-2
    image: consul:1.8.0
    restart: always
    ports:
      - 28300:8300
      - 28301:8301
      - 28301:8301/udp
      - 28302:8302
      - 28302:8302/udp
      - 28400:8400
      - 28500:8500
      - 28600:8600
      - 28600:8600/udp
    networks:
        default:
            ipv4_address: 192.168.255.242
    environment:
      CONSUL_LOCAL_CONFIG: >-
        {
          "bootstrap_expect": 3,
          "client_addr": "0.0.0.0",
          "datacenter": "Us-Central",
          "data_dir": "/var/consul",
          "domain": "consul",
          "enable_script_checks": true,
          "dns_config": {
              "enable_truncate": true,
              "only_passing": true
          },
          "encrypt": "6uZf92Qa7dFgGnQ1zh8Hn0MwnRh1bRAOlE481Mv4+cU=",
          "leave_on_terminate": true,
          "log_level": "INFO",
          "rejoin_after_leave": true,
          "server": true,
          "telemetry": {
              "prometheus_retention_time": "24h",
              "disable_hostname": true
          },                
          "start_join": [
              "192.168.255.241",
              "192.168.255.242",
              "192.168.255.243"
          ],
          "ui": true
        }    
    command: "agent"
    
  consul-server-3:
    container_name: tutorial-consul-server-3
    image: consul:1.8.0
    restart: always
    ports:
      - 38300:8300
      - 38301:8301
      - 38301:8301/udp
      - 38302:8302
      - 38302:8302/udp
      - 38400:8400
      - 38500:8500
      - 38600:8600
      - 38600:8600/udp
    networks:
        default:
            ipv4_address: 192.168.255.243
    environment:
      CONSUL_LOCAL_CONFIG: >-
        {
          "bootstrap_expect": 3,
          "client_addr": "0.0.0.0",
          "datacenter": "Us-Central",
          "data_dir": "/var/consul",
          "domain": "consul",
          "enable_script_checks": true,
          "dns_config": {
              "enable_truncate": true,
              "only_passing": true
          },
          "encrypt": "6uZf92Qa7dFgGnQ1zh8Hn0MwnRh1bRAOlE481Mv4+cU=",
          "leave_on_terminate": true,
          "log_level": "INFO",
          "rejoin_after_leave": true,
          "server": true,
          "telemetry": {
              "prometheus_retention_time": "24h",
              "disable_hostname": true
          },                
          "start_join": [
              "192.168.255.241",
              "192.168.255.242",
              "192.168.255.243"
          ],
          "ui": true
        }    
    command: "agent"

  consul-agent-1:
    container_name: tutorial-consul-agent-1
    image: consul:1.8.0
    restart: always
    networks:
        default:
            ipv4_address: 192.168.255.244
    environment:
      CONSUL_LOCAL_CONFIG: >-
        {
          "server": false,
          "datacenter": "Us-Central",
          "data_dir": "/var/consul",
          "encrypt": "6uZf92Qa7dFgGnQ1zh8Hn0MwnRh1bRAOlE481Mv4+cU=",
          "log_level": "INFO",
          "leave_on_terminate": true,
          "start_join": [
              "192.168.255.242"
          ]
        }    
    command: "agent"

  consul-agent-2:
    container_name: tutorial-consul-agent-2
    image: consul:1.8.0
    restart: always
    networks:
        default:
            ipv4_address: 192.168.255.245
    environment:
      CONSUL_LOCAL_CONFIG: >-
        {
          "server": false,
          "datacenter": "Us-Central",
          "data_dir": "/var/consul",
          "encrypt": "6uZf92Qa7dFgGnQ1zh8Hn0MwnRh1bRAOlE481Mv4+cU=",
          "log_level": "INFO",
          "leave_on_terminate": true,
          "start_join": [
              "192.168.255.243"
          ]
        }    
    command: "agent"

networks:
  default:
    external:
      name: census-net
