version: '3'

services:
  census:
    image: census:0.0.1-SNAPSHOT
    ports:
      - "1301:1301"
    environment:
      - spring.profiles.active=consul
      - spring.cloud.consul.host=consul-server-1
      - PORT_EXTERNAL=1301

  census-zipcode-1:
    image: census-zipcode:0.0.1-SNAPSHOT
    ports:
      - "14011:14011"
    environment:
      - spring.profiles.active=consul
      - spring.cloud.consul.host=consul-server-1
      - PORT_EXTERNAL=14011

  census-zipcode-2:
    image: census-zipcode:0.0.1-SNAPSHOT
    ports:
      - "14012:14012"
    environment:
      - spring.profiles.active=consul
      - spring.cloud.consul.host=consul-server-1
      - PORT_EXTERNAL=14012

  census-demography-1:
    image: census-demography:0.0.1-SNAPSHOT
    ports:
      - "14021:14021"
    environment:
      - spring.profiles.active=consul
      - spring.cloud.consul.host=consul-server-1
      - PORT_EXTERNAL=14021

  census-demography-2:
    image: census-demography:0.0.1-SNAPSHOT
    ports:
      - "14022:14022"
    environment:
      - spring.profiles.active=consul
      - spring.cloud.consul.host=consul-server-1
      - PORT_EXTERNAL=14022

networks:
  default:
    external:
      name: consul-net
